'use strict';
const { consumerNav } = require('./consumer-nav');
function esc(s) {
  return String(s == null ? '' : s).replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>').replace(/"/g, '"');
}
function money(cents) { return '$' + (Number(cents || 0) / 100).toFixed(2); }
const FOOTER = '<footer><nav class="footer-links" aria-label="Legal"><a href="/tp">T & P</a><a href="/support">Support</a></nav><span><a href="https://aorilalabs.com" data-local-site="labs">Aorila Labs</a></span></footer>';
function wrap({ title, body, user, commercial }) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${esc(title)} — Aorila</title><link rel="icon" href="/favicon.svg" type="image/svg+xml" /><link rel="stylesheet" href="/styles.css" /></head><body data-site="consumer"${commercial ? ' class="commercial"' : ''}>${consumerNav({ accountUser: user, commercialCurrent: Boolean(commercial) })}${body}${FOOTER}<script src="/site.js"></script><script src="/price.js"></script><script src="/console.js"></script></body></html>`;
}
function authForm({ mode, error, next }) {
  const signup = mode === 'signup';
  return wrap({ title: signup ? 'Create account' : 'Sign in', user: null, body: `<main><section class="hero compact"><p class="hero-badge">Account</p><h1>${signup ? 'Create an Aorila account.' : 'Sign in to Aorila.'}</h1><p class="lede">${signup ? 'One account for pods, billing, and commercial bookings.' : 'Open the console. Start a GPU. Watch spend.'}</p>${error ? `<p class="form-status err">${esc(error)}</p>` : ''}<form class="waitlist" method="post" action="${signup ? '/signup' : '/login'}"><input type="hidden" name="next" value="${esc(next || '/console')}" />${signup ? '<label>Name<input name="name" required autocomplete="name" /></label><label>Company<input name="company" autocomplete="organization" /></label>' : ''}<label>Email<input type="email" name="email" required autocomplete="email" /></label><label>Password<input type="password" name="password" required minlength="8" /></label>${signup ? '<label>Account type<select name="plan"><option value="on-demand">On-demand</option><option value="commercial">Commercial</option></select></label>' : ''}<button class="cta primary" type="submit">${signup ? 'Create account' : 'Sign in'}</button></form><p class="price-note">${signup ? 'Already have an account? <a href="/login">Sign in</a>.' : 'No account? <a href="/signup">Create one</a>.'}</p></section></main>` });
}
function machineRows(machines) {
  if (!machines.length) return '<p class="ms-note">No machines yet. Pick a live SKU and start it.</p>';
  return '<div class="table-wrap"><table class="sku-table"><thead><tr><th>Machine</th><th>Status</th><th>$ / hour</th><th></th></tr></thead><tbody>' + machines.map((m) => `<tr><td>${esc(m.name || m.sku)}<div class="price-note">${esc(m.region || '')} · ${esc(m.id)}</div></td><td>${esc(m.status)}${m.message ? `<div class="price-note">${esc(m.message)}</div>` : ''}</td><td>$${Number(m.usdPerHour || 0).toFixed(3)}</td><td>${m.status === 'stopped' || m.status === 'failed' ? '' : `<form method="post" action="/console/stop/${esc(m.id)}"><button class="cta ghost" type="submit">Stop</button></form>`}</td></tr>`).join('') + '</tbody></table></div>';
}
function bookingRows(bookings) {
  if (!bookings.length) return '<p class="ms-note">No planned VMs or reserved hours yet.</p>';
  return '<div class="table-wrap"><table class="sku-table"><thead><tr><th>Request</th><th>Kind</th><th>Window</th><th>Status</th></tr></thead><tbody>' + bookings.map((b) => `<tr><td>${esc(b.name || b.sku)}</td><td>${esc(b.kind)}</td><td>${esc(b.window || '—')}</td><td>${esc(b.status)}</td></tr>`).join('') + '</tbody></table></div>';
}
function consolePage({ user, balanceCents, machines, bookings, error, notice }) {
  return wrap({ title: 'Console', user, body: `<main><section class="hero compact"><p class="hero-badge">Console</p><h1>Hello, ${esc(user.name)}.</h1><p class="lede">Balance ${money(balanceCents)}. Start a live pod or book commercial capacity.</p>${error ? `<p class="form-status err">${esc(error)}</p>` : ''}${notice ? `<p class="form-status ok">${esc(notice)}</p>` : ''}<div class="cta-row"><a class="cta primary" href="/pods">Start a pod</a><a class="cta ghost" href="/console/billing">Add credits</a><a class="cta ghost" href="/commercial/console">Commercial portal</a></div></section><section class="section undivided"><h2>Machines</h2>${machineRows(machines)}</section><section class="section"><h2>Commercial bookings</h2>${bookingRows(bookings)}</section><section class="section"><h2>Live catalog</h2><div data-live-prices data-start="1"></div></section></main>` });
}
function billingPage({ user, balanceCents, error, notice }) {
  return wrap({ title: 'Billing', user, body: `<main><section class="hero compact"><p class="hero-badge">Billing</p><h1>Workspace credits</h1><p class="lede">Current balance ${money(balanceCents)}.</p>${error ? `<p class="form-status err">${esc(error)}</p>` : ''}${notice ? `<p class="form-status ok">${esc(notice)}</p>` : ''}<form class="waitlist" method="post" action="/console/credits"><label>Amount<select name="dollars"><option value="25">$25</option><option value="100" selected>$100</option><option value="500">$500</option><option value="1000">$1,000</option></select></label><button class="cta primary" type="submit">Add credits</button></form><p class="price-note">This ledger funds start/stop in the console.</p><div class="cta-row"><a class="cta ghost" href="/console">Back to console</a></div></section></main>` });
}
function commercialConsole({ user, bookings, error, notice }) {
  return wrap({ title: 'Commercial portal', user, commercial: true, body: `<div class="ms-shell"><nav class="ms-rail" aria-label="Commercial"><a href="/commercial">Overview</a><a href="/commercial/vms">Planned VMs</a><a href="/commercial/reserved">Reserved</a><a href="/commercial/console" aria-current="page">Portal</a><a href="/console">On-demand console</a><a href="/console/billing">Billing</a></nav><main class="ms-main"><p class="ms-kicker">Commercial</p><h1>Organization portal</h1><p class="lede">${esc(user.company || user.name)} — planned VMs and reserved hours.</p>${error ? `<p class="form-status err">${esc(error)}</p>` : ''}${notice ? `<p class="form-status ok">${esc(notice)}</p>` : ''}<h2>Request capacity</h2><form class="waitlist" method="post" action="/commercial/console/book"><label>Kind<select name="kind"><option value="planned-vm">Planned VM</option><option value="reserved">Reserved hours</option></select></label><label>Machine / SKU<input name="sku" required placeholder="Aorila H100 80GB" /></label><label>Window<input name="window" required placeholder="14 days starting Oct 1" /></label><label>Notes<textarea name="notes" rows="3"></textarea></label><button class="cta primary" type="submit">Submit request</button></form><h2>Open requests</h2>${bookingRows(bookings)}</main></div>` });
}
module.exports = { authForm, consolePage, billingPage, commercialConsole, wrap };
