#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { MARKETING_SLUGS, renderMarketingPage } = require('../lib/marketing-pages');
const { COMMERCIAL_SLUGS, renderCommercialPage } = require('../lib/commercial-pages');
const siteRuntime = require('../public/site.js');

const ROOT = path.join(__dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const SITES_DIR = path.join(ROOT, 'sites');
const DIST_DIR = path.join(ROOT, 'dist');
const SITE = String(process.argv[2] || '').trim().toLowerCase();
const VALID_SITES = new Set(['consumer', 'labs', 'robotics']);
const STATIC_API_ORIGIN = String(process.env.STATIC_API_ORIGIN || '').trim();
const STATIC_DASHBOARD_ORIGIN = String(process.env.STATIC_DASHBOARD_ORIGIN || '').trim();
// Parent (Aorila) console home. Entities share only login; the console is never
// on an API host. api.aorila.com does not exist.
const STATIC_CONSOLE_ORIGIN = String(process.env.STATIC_CONSOLE_ORIGIN || '').trim().replace(/\/+$/, '') || 'https://console.aorila.com';
// Per-site API origins. Never api.aorila.com (does not exist); API hosts are JSON-only.
const SITE_API_ORIGIN = {
  consumer: STATIC_API_ORIGIN || 'https://api.aorilalabs.com',
  labs: STATIC_API_ORIGIN || 'https://dashboard.aorilalabs.com',
  robotics: STATIC_API_ORIGIN || 'https://api.aorilalabs.com',
};

if (!VALID_SITES.has(SITE)) {
  console.error('Usage: node scripts/build-site.js <consumer|labs|robotics>');
  process.exit(1);
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function copyDir(src, dest) {
  ensureDir(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}

function withApiMeta(html) {
  const apiOrigin = SITE_API_ORIGIN[SITE] || STATIC_API_ORIGIN;
  if (!apiOrigin) return html;
  const meta = `<meta name="${siteRuntime.META_NAME}" content="${apiOrigin}" />`;
  if (html.includes(`name="${siteRuntime.META_NAME}"`)) return html;
  return html.replace(/<head>/i, `<head>\n  ${meta}`);
}

function writeHtml(root, relativePath, html) {
  const normalized = relativePath.replace(/^\/+/, '');
  const full = path.join(root, normalized);
  ensureDir(path.dirname(full));
  fs.writeFileSync(full, withApiMeta(html));
}

function writeRoute(root, route, html) {
  const clean = String(route || '').replace(/^\/+/, '').replace(/\/+$/, '');
  if (!clean) {
    writeHtml(root, 'index.html', html);
    return;
  }
  writeHtml(root, `${clean}.html`, html);
  writeHtml(root, path.join(clean, 'index.html'), html);
}

// Per-site GA4 measurement IDs. Redirect pages generated by the build get the
// ID of the site they belong to — never another entity's property.
const SITE_GA_ID = {
  consumer: 'G-064VLFE5ZY',
  labs: 'G-68Z6SM8C4B',
  robotics: '',
};

function gaSnippet(gaId) {
  if (!gaId) return '';
  return `<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=${gaId}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '${gaId}');
</script>
`;
}

function redirectPage(title, target) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
${gaSnippet(SITE_GA_ID[SITE] || '')}  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="refresh" content="0; url=${target}" />
  <title>${title}</title>
  <link rel="canonical" href="${target}" />
</head>
<body>
  <p>Redirecting to <a href="${target}">${target}</a>…</p>
  <script>location.replace(${JSON.stringify(target)});</script>
</body>
</html>`;
}

function buildConsumer(targetDir) {
  // The consumer face (aorila.com) is the Vivet-exact replica: ship it verbatim.
  // No on-site selling — the bag holds a $50 refundable robot-presale deposit
  // whose CTA links out to robotics.aorila.com.
  copyDir(path.join(ROOT, 'consumer-site'), targetDir);
  const apiOrigin = STATIC_CONSOLE_ORIGIN;
  // NOTE: 'login' and 'signup' are REAL pages in consumer-site/ (standalone auth
  // cards, no header/footer). They must NOT be overwritten with redirect stubs —
  // that created a redirect loop with console.aorila.com. Only console-only
  // routes get stubs here. 'signin'/'register' stubs are safe: the console
  // 301s them to the real /login and /signup pages.
  for (const route of ['console', 'account', 'dashboard', 'signin', 'register']) {
    writeRoute(targetDir, route, redirectPage(`Redirecting to ${route}`, `${apiOrigin}/${route}`));
  }
  // Preserve old inbound URLs by pointing them at their replica pages.
  writeRoute(targetDir, 'models', redirectPage('Redirecting to divisions', '/divisions/'));
  writeRoute(targetDir, 'enterprise', redirectPage('Redirecting to divisions', '/divisions/'));
  writeRoute(targetDir, 'privacy', redirectPage('Redirecting to privacy policy', '/policies/privacy'));
  writeRoute(targetDir, 'terms', redirectPage('Redirecting to terms of service', '/policies/terms'));
  // Stale pages removed from the repo still linger on the static host (deploys
  // overlay instead of wiping). Overwrite them with redirects to divisions.
  for (const route of ['ai', 'ai/api', 'ai/atraly-chat', 'ai/atraly-plus', 'ai/atraly-pro',
                       'compute', 'compute/cpu-pods', 'compute/gpu-pods', 'compute/credit-pack']) {
    writeRoute(targetDir, route, redirectPage('Redirecting to divisions', '/divisions/'));
  }
  // Deleted pages: home-robot product page removed (products page is /robots/),
  // journal renamed to blog. Redirect so the old URLs never serve stale content.
  writeRoute(targetDir, 'robots/home-robot', redirectPage('Redirecting to robots', '/robots/'));
  writeRoute(targetDir, 'journal', redirectPage('Redirecting to blog', '/blog/'));
}

function escHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Work-log rows are rendered at build time from sites/labs/work-log.json —
// the JSON is the single source of truth. Adding entries = editing the JSON.
// Every entry gets a stable slug (date + project + run, hyphenated) used for
// its detail page at /work-log/<slug>/.
function wlSlug(entry, used) {
  const base = [entry.date, entry.project, entry.run]
    .filter(Boolean).join(' ')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  let slug = base;
  let i = 2;
  while (used.has(slug)) slug = base + '-' + (i++);
  used.add(slug);
  return slug;
}

function wlRowsHtml(entries, indent) {
  return entries.map(function (e) {
    const href = '/work-log/' + e.slug;
    return indent + '<div class="wl-row">' +
      '<a href="' + href + '">' + escHtml(e.date) + '</a>' +
      '<a href="' + href + '">' + escHtml(e.project) + '</a>' +
      '<a href="' + href + '" class="r">' + escHtml(e.run) + '</a>' +
      '<a href="' + href + '" class="r">' + escHtml(e.status) + '</a></div>';
  }).join('\n');
}

// Detail page for one work-log entry. No invented copy — just the row's own
// fields, an honest "No updates yet." placeholder, and a plain-text
// mailto link for suggestions.
// Unique meta description per entry, built from its own fields.
function wlEntryDesc(entry) {
  return [entry.date, [entry.project, entry.run].filter(Boolean).join(' '), entry.status]
    .filter(Boolean).join(' — ') + '. A work log entry from Aorila Labs.';
}

function wlDetailHtml(template, entry) {
  const titleBits = [entry.project, entry.run].filter(Boolean).join(' ');
  const subject = encodeURIComponent(
    'Work log suggestion: ' + [entry.date, entry.project, entry.run].filter(Boolean).join(' ')
  );
  return template
    .split('<!--ENTRY_TITLE-->').join(escHtml(titleBits + ' — Work log'))
    .split('<!--ENTRY_H1-->').join(escHtml(titleBits))
    .split('<!--ENTRY_DESC-->').join(escHtml(wlEntryDesc(entry)))
    .split('<!--ENTRY_SLUG-->').join(entry.slug)
    .split('<!--ENTRY_DATE-->').join(escHtml(entry.date))
    .split('<!--ENTRY_PROJECT-->').join(escHtml(entry.project))
    .split('<!--ENTRY_RUN-->').join(escHtml(entry.run) || '&mdash;')
    .split('<!--ENTRY_STATUS-->').join(escHtml(entry.status))
    .split('<!--ENTRY_SUBJECT-->').join(subject);
}

async function buildLabs(targetDir) {
  const labsDir = path.join(SITES_DIR, 'labs');
  const rawEntries = JSON.parse(fs.readFileSync(path.join(labsDir, 'work-log.json'), 'utf8'));
  const usedSlugs = new Set();
  const wlEntries = rawEntries.map(function (e) {
    return Object.assign({}, e, { slug: wlSlug(e, usedSlugs) });
  });
  const wlJson = JSON.stringify(wlEntries);
  function labsPage(name, indent, entries) {
    return fs.readFileSync(path.join(labsDir, name), 'utf8')
      .split('<!--WORKLOG_ROWS-->').join(wlRowsHtml(entries || wlEntries, indent))
      .split('<!--WORKLOG_JSON-->').join(wlJson);
  }
  // Aorila Labs is a front page plus /get-involved and /work-log. Every
  // other route that ever existed on this host bounces back to the front
  // page — the static host overlays deploys instead of wiping, so these
  // deterministic stubs overwrite the ghosts of deleted pages.
  // NOTE: the pages are written with rendered work-log rows (no
  // api-origin meta, no bounce script). work-log.json ships alongside so
  // the data file is publicly readable too.
  // Front page shows the 10 most recent entries; /work-log shows all (paginated).
  fs.writeFileSync(path.join(targetDir, 'index.html'), labsPage('index.html', '        ', wlEntries.slice(0, 10)));
  fs.copyFileSync(path.join(labsDir, 'work-log.json'), path.join(targetDir, 'work-log.json'));
  const getInvolved = fs.readFileSync(path.join(labsDir, 'get-involved.html'), 'utf8');
  fs.writeFileSync(path.join(targetDir, 'get-involved.html'), getInvolved);
  ensureDir(path.join(targetDir, 'get-involved'));
  fs.writeFileSync(path.join(targetDir, 'get-involved', 'index.html'), getInvolved);
  const workLog = labsPage('work-log.html', '          ');
  fs.writeFileSync(path.join(targetDir, 'work-log.html'), workLog);
  ensureDir(path.join(targetDir, 'work-log'));
  fs.writeFileSync(path.join(targetDir, 'work-log', 'index.html'), workLog);
  // Per-entry detail pages. NOTE (2026-09-25): Render resolves the clean
  // URL /work-log/<slug> to work-log/<slug>/index.html, NOT to the flat
  // <slug>.html — verified live. So a redirect stub at the directory path
  // would hijack the canonical URL itself (infinite self-redirect). Both
  // copies therefore carry the full page; the slashless canonical +
  // slashless sitemap + slashless links declare the one true URL.
  const entryTemplate = fs.readFileSync(path.join(labsDir, 'work-log-entry.html'), 'utf8');
  for (const entry of wlEntries) {
    const detail = wlDetailHtml(entryTemplate, entry);
    fs.writeFileSync(path.join(targetDir, 'work-log', entry.slug + '.html'), detail);
    ensureDir(path.join(targetDir, 'work-log', entry.slug));
    fs.writeFileSync(path.join(targetDir, 'work-log', entry.slug, 'index.html'), detail);
  }
  // Share image + branded 404.
  fs.copyFileSync(path.join(labsDir, 'og-image.png'), path.join(targetDir, 'og-image.png'));
  fs.copyFileSync(path.join(labsDir, '404.html'), path.join(targetDir, '404.html'));
  const home = 'https://aorilalabs.com/';
  for (const route of ['terms', 'marketplace', 'developers', 'pricing', 'support',
                       'tp', 'docs', 'sell', 'console', 'compute', 'api',
                       'training', 'models', 'trust', 'contact']) {
    writeRoute(targetDir, route, redirectPage('Aorila Labs', home));
  }
  // robots.txt + sitemap.xml for the Labs site (front page + get-involved +
  // work-log + every work-log entry detail page).
  fs.writeFileSync(
    path.join(targetDir, 'robots.txt'),
    'User-agent: *\nAllow: /\nSitemap: https://aorilalabs.com/sitemap.xml\n'
  );
  const lastmod = new Date().toISOString().slice(0, 10);
  const sitemapUrls = [
    `${home}`,
    `${home}get-involved`,
    `${home}work-log`,
  ].concat(wlEntries.map(function (e) { return `${home}work-log/${e.slug}`; }));
  fs.writeFileSync(
    path.join(targetDir, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    sitemapUrls.map(function (u) { return `  <url><loc>${u}</loc><lastmod>${lastmod}</lastmod></url>`; }).join('\n') +
    `\n</urlset>\n`
  );
}

function buildRobotics(targetDir) {
  const html = fs.readFileSync(path.join(SITES_DIR, 'robotics', 'index.html'), 'utf8');
  writeRoute(targetDir, '', html);
}

const targetDir = path.join(DIST_DIR, SITE);
fs.rmSync(targetDir, { recursive: true, force: true });
ensureDir(targetDir);
copyDir(PUBLIC_DIR, targetDir);

if (SITE === 'consumer') { buildConsumer(targetDir); done(); }
else if (SITE === 'labs') buildLabs(targetDir).then(done, (err) => { console.error(err); process.exit(1); });
else { buildRobotics(targetDir); done(); }

function done() {
  console.log(`Built ${SITE} site into ${path.relative(ROOT, targetDir)}`);
}
